apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsodev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsodev
  template:
    metadata:
      labels:
        app: devopsodev
    spec:
      containers:
      - name: devopsodev-kub
        image: ahmettakci/devsecops:v5
        ports:
        - containerPort: 8080
